### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by PulseLottery** [Nahuel149/FutBinDataEAFC24#4]
TotalPages = str(bs.findAll('li', {'class': 'page-item '})[-1].text).strip()

IndexError: list index out of range

**Comment by PulseLottery** [comment]
Anyone?

**Comment by Nahuel149** [comment]
They updated the website with a new attribute and now it is fixed, Regarding your error, you need to try a different solution, for me, it doesn't display so be sure that you installed all the libraries just in case, but if you already have everything you could add something like this:

except IndexError:
    TotalPages = '1'  # Set a default value in case of an error
    
 In order to Handle the IndexError if no elements are found

**Comment by Nahuel149** [comment]
Check the README and tell me if it's working for you now, for me I just finished running the script and zero problems.
